version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dh
      POSTGRES_USER: dh
      POSTGRES_PASSWORD: dh
    ports: ["5432:5432"]
    volumes: ["pg:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: ["9000:9000","9001:9001"]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes: ["s3:/data"]
  rabbit:
    image: rabbitmq:3-management-alpine
    ports: ["5672:5672","15672:15672"]
volumes:
  pg:
  s3:
